name: 自动部署

on:
  push:
    branches: [master,dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 检出分支
        uses: actions/checkout@v3

      - name: 2. 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 3. 缓存 node
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: 4. 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install --save

      - name: 5. 构建
        run: |
          npm run build:prod

      - name: 6. 推送到服务器
        uses: ilCollez/ssh-scp-deploy@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }} #ip
          port: ${{ secrets.SERVER_PORT }} #端口
          username: ${{ secrets.SERVER_USER }} #用户名
          key: ${{ secrets.SERVER_ACCESS_TOKEN }} #服务器密钥
          files: | #上传文件
              dist/*
          remote-path: ${{ secrets.SERVER_TARGET }} #远程路径
          clean: true #是否清理远程路径

      - name: 7. 安装 Python #没有使用腾讯云cdn可删除该步骤
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: 8. 安装依赖
        run: |
          pip install --upgrade pip
          pip install tencentcloud-sdk-python
          pip install tencentcloud-sdk-python-cdn

      - name: 9. 刷新腾讯云cdn #没有使用腾讯云cdn可删除该步骤
        run: |
          python cdn.py ${{ secrets.TENCENT_SECRETID }} ${{ secrets.TENCENT_SECRETKEY }} ${{ secrets.CDN_URL }}
